### ISSUE TITLE
after 3.5 update

### ISSUE THREAD

**Issue by 759892593** [Renji-kun/Dickware#11]
I am happy to see antiaim crash problem was solved，but thirdperson still not work，may be you can change back the thirdperson code to ‘’180204.01r ‘’。skinchanger chose weopens show fonts error。

**Comment by 759892593** [comment]
what a big bug I just found,when I shoot enemy,game crash.wow.

**Comment by Renji-kun** [comment]
Can you provide more details about your issues?(your system/game language, cheat configs etc.)

**Comment by 759892593** [comment]
of course，how could I communicate with you？discord?

**Comment by 759892593** [comment]
windows10 Chinese,config was make my self,but I use ‘’180204.01r ‘’ ,expect skinchanger,others are good

**Comment by Renji-kun** [comment]
> of course，how could I communicate with you？discord?
Well, add me on Discord ドラゴンロリ#8548
